name: "Deploy App to Fly.io"

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: backend/src/main/resources/static

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21' # must match the version in the pom.xml
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with maven
        run: mvn -B package --file backend/pom.xml

      - uses: actions/upload-artifact@v4
        with:
          name: SitemapDiff.jar
          path: backend/target/sitemapdiff.jar # must match the finalName in the pom.xml

  push-to-docker-hub:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: SitemapDiff.jar
          path: backend/target

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # must match the name of the Dockerhub account
          password: ${{ secrets.DOCKERHUB_PASSWORD }} # must match the password of the Dockerhub account

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_TAG }} # Example: username/project:latest
          context: .

  deploy:
    name: Trigger Fly.io deployment
    runs-on: ubuntu-latest
    needs: push-to-docker-hub
    environment:
      name: SitemapDiff
      url: https://sitemapdiff.samuelgesang.de/
    steps:
      - name: Trigger Fly.io Deployment
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          curl -X POST "https://api.fly.io/apps/sitemapdiff8/deploys" \
          -H "Authorization: Bearer $FLY_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"strategy":"immediate"}'
